### ISSUE TITLE
Include data-type constraints in the JSON schema 

### ISSUE THREAD

**Issue by floydtree** [ocsf/ocsf-server#109]
The current json-schema, e.g. https://schema.ocsf.io/schema/1.3.0/objects/network_endpoint doesn't include the data-type constraints defined in the dictionary - https://github.com/ocsf/ocsf-schema/blob/main/dictionary.json#L4839. 

These constraints are in the form of regex, max_length, range and values. All these can be represented in the json-schema that is rendered by our server, helping json-schema based validation use-cases and perform value specific validation. JSON spec has a few [built-in string formats](https://json-schema.org/understanding-json-schema/reference/string#built-in-formats) that can be leveraged as well.

Further, we can also add `constant` values for attributes such as `class_name`, `category_name` etc, as we render the json-schema of an event class. 

References - 
1. https://json-schema.org/understanding-json-schema/reference/const
2. https://json-schema.org/understanding-json-schema/reference/regular_expressions
3. https://json-schema.org/understanding-json-schema/reference/string
4. https://json-schema.org/understanding-json-schema/reference/numeric#range

**Comment by mikeradka** [comment]
@floydtree was this resolved by https://github.com/ocsf/ocsf-server/pull/112? Could it be closed out or does it need additional effort?

**Comment by floydtree** [comment]
@mikeradka nope, it was partially fixed. There are a few more to go.
